### ISSUE TITLE
When opening the search menu, set the forcus to the search

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/VisualProgrammingEditor#267]
- [x] set focus of the input 
- [x] press `down`  `up` to navigate between the input and treeview
- [x] figure out why treeview is not scrolling
- [ ] when we have more items, the view is not correct

**Comment by xp1632** [comment]
[1d2b8bf](https://github.com/Max-ChenFei/VisualProgrammingEditor/commit/1d2b8bf9391fdea3eac11ea545a92a3aa89030aa) This commit of set keyDownEvent in Searchinput and give focus to Treeview Reference didn't work, I'll dig into details tomorrow.

**Comment by xp1632** [comment]
> [1d2b8bf](https://github.com/Max-ChenFei/VisualProgrammingEditor/commit/1d2b8bf9391fdea3eac11ea545a92a3aa89030aa) This commit of set keyDownEvent in Searchinput and give focus to Treeview Reference didn't work, I'll dig into details tomorrow.

Also, the in-list arrowdown event also doesn't work.  Maybe the intinial focus on searchinput and arrowdown event are conflicted demands

**Comment by xp1632** [comment]
Reason could be:  
1. Focus event is only limited to the element itself,non-bubble up to parent.

So the refrence of Treeview should be the most inside treeviewItem. 

2. Also the structure of SearchedMenu is complicated, because the Controlled TreeView and the rest ‘Add Comment’ are not defined/created in the same place or same time.3. 
We need to carefully choose the reference of TreeeivwItem, make sure it’s the exact one, not any parent.

**Comment by Max-ChenFei** [comment]
![Esc23324723333](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/28513798/bd6b27cd-3322-408e-8e25-7ff41506cca3)

**Comment by xp1632** [comment]
![Animation4](https://github.com/Max-ChenFei/VisualProgrammingEditor/assets/8528052/44e4c693-c42c-4711-a0bb-010a1e4f0307)
